verbose: false
quickBench:
    blockId: 22
    blockData: 1
    alternateBlockId: 0
    alternateBlockData: 0
    itemId: 58
    title: QuickBench
    enableCrafting: true
    minSizeRows: 0
    showOtherRoutes: false
    craftStack: true
    maxStackSize: 64
    useDeniedMessage: 'You do not have permission to use this QuickBench.'
    placeDeniedMessage: 'You do not have permission to place this QuickBench.'
    destroyDeniedMessage: 'You do not have permission to destroy this QuickBench.'
