name: QuickBench
main: com.exphc.QuickBench.QuickBench
version: 3.0.4
permissions:
    quickbench.*:
        children:
            quickbench.use: true
            quickbench.showHidden: true
            quickbench.craftStack: true
            quickbench.place: true
            quickbench.destroy: true
        default: false
    quickbench.use:
        description: Allows you to use a QuickBench
        default: true
    quickbench.showHidden:
        description: Allows you to craft secret recipes from IC2
        default: true
    quickbench.craftStack:
        description: Allows you to craft stacks of items at once
        default: true
    quickbench.place:
        description: Allows you to place a QuickBench 
        default: true
    quickbench.destroy:
        description: Allows you to destroy a QuickBench
        default: true

